@startuml

interface Coffee {
    {abstract} +getDescription(): String
    {abstract} +cost(): double
}

class BasicCoffee {
    +getDescription(): String
    +cost(): double
}

abstract class CoffeeDecorator {
    -decoratedCoffee: Coffee
    +CoffeeDecorator(decoratedCoffee: Coffee)
    +getDescription(): String
    +cost(): double
}

class MilkDecorator {
    +MilkDecorator(decoratedCoffee: Coffee)
    +getDescription(): String
    +cost(): double
}

class SugarDecorator {
    +SugarDecorator(decoratedCoffee: Coffee)
    +getDescription(): String
    +cost(): double
}

class Client {
}

Coffee <|.. BasicCoffee
Coffee <|-- CoffeeDecorator
CoffeeDecorator <|-- MilkDecorator
CoffeeDecorator <|-- SugarDecorator
Client --> Coffee

@enduml
