@startuml Facade

class Engine {
    + start()
    + stop()
}

class AirConditioner {
    + turnOn()
    + turnOff()
}

class MusicPlayer {
    + playMusic()
    + stopMusic()
}

class CarFacade {
    - engine: Engine
    - airConditioner: AirConditioner
    - musicPlayer: MusicPlayer
    + startCar()
    + stopCar()
}


CarFacade "1" --> "1" Engine: Contains
CarFacade "1" --> "1" AirConditioner: Contains
CarFacade "1" --> "1" MusicPlayer: Contains
Client --> CarFacade: Uses

@enduml
