@startuml Iterator

interface BookIterator {
    {abstract} +hasNext(): boolean
    {abstract} +next(): String
}

class BookListIterator {
    -books: List<String>
    -position: int
    +BookListIterator(books: List<String>)
    +hasNext(): boolean
    +next(): String
}

interface BookCollection {
    {abstract} +createIterator(): BookIterator
}

class Library {
    -books: List<String>
    +Library()
    +addBook(book: String): void
    +createIterator(): BookIterator
}

class Client {}

BookIterator <|.. BookListIterator
BookCollection <|.. Library
BookIterator <-- Library
Client --> Library

@enduml
